# -*- mode: ruby -*-
# vi: set ft=ruby :

# variables
VAGRANTFILE_API_VERSION = "2"
ip_address = "172.23.23.23"
project_name = "node"

# configuration start
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # vm configuration
  config.vm.box = "kungfuice/ubuntu64-java"

	# Networking
  # set up hostmanager to reach server at node.local:port
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.define project_name do |node|
    node.vm.hostname = project_name + ".local"
    node.vm.network :private_network, ip: ip_address
    node.hostmanager.aliases = ["www." + project_name + ".local"]
  end

  config.vm.provision :hostmanager

	config.vm.network "forwarded_port", host: 3000, guest: 3000
  config.vm.network "forwarded_port", host: 9000, guest: 9000
  config.vm.network "forwarded_port", host: 7474, guest: 7474
	
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
   config.vm.synced_folder "../angular/", "/srv/angular_projects"

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #

	config.vm.provision :shell, path: "provisioning/setup.sh"

	# Configurate the virtual machine to use 2GB of RAM
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

	# config.vm.provision :chef_solo do |chef|
		# chef.cookbooks_path = ["cookbooks", "site-cookbooks"]

		# chef.add_recipe "apt"
		# chef.add_recipe "nodejs"
		# chef.add_recipe "ruby_build"
		# chef.add_recipe "rbenv::user"
		# chef.add_recipe "rbenv::vagrant"

		# chef.json = {
      # rbenv: {
        # user_installs: [{
          # user: 'vagrant',
          # rubies: ["2.1.2"],
          # global: "2.1.2",
          # gems: {
            # "2.1.2" => [
              # { name: "bundler" }
            #]
          #}
        #}]
      #}
    #}
	#end
end
